### ISSUE TITLE
Suggestion: Actual Sheathe and Draw instead of using Gold Saucer emotes?

### ISSUE THREAD

**Issue by Maxunit** [fitzchivalrik/gentletouch#11]
Hello fitzchivalrik,

I gave Gentletouch another spin after a long time. Saw that you added DualSense support, including Adaptive Triggers! Really awesome!

That aside:

You are using the /sheathe motion and /draw motion emotes for sheathing and drawing your weapon, which in return requires the Gold Saucer emotes.

Wouldn't it be easier to just use /bm and /bm off to draw and sheathe your weapon?

PS: I just tested it out with a locally modified code and it works just fine.

EDIT:

A question: Can it be detected if the character did auto-draw or auto-sheathe the weapon? It seems to be a fixed conditional (?) as of now?

**Comment by fitzchivalrik** [comment]
Thanks for using the plugin.

> Wouldn't it be easier to just use /bm and /bm off to draw and sheathe your weapon?

You can already do that vanilla via `L1 + R1` (first press L1, then R1) - I specifically wanted to use `/draw` & `/sheathe`[^1] because it looks better x).

The function essentially is the same as having both of those commands as a macro (what I did before), just one button instead of two. Drawing/Sheathing only happens on button input - there is nothing automatic.
You can disable the functionality and have Macro #97 and #96 be `/draw` and `/sheathe`, using PSHome and Create to do it via two buttons.
As usual, there is no guaranteed safety when using plugins, but I felt that there is no inherent greater risk.

[^1]: Both, which, unfortunately, do not work while moving <.<, so it defaults to normal sheathe/draw then.

**Comment by Maxunit** [comment]
Oh right, totally forgot about `L1 + R1` for that. It makes sense then ^^

And nah, there shouldn't be any risk x)

(Ticket can be closed then?)
