### ISSUE TITLE
6.1 Support

### ISSUE THREAD

**Issue by VictorFong-SE** [fitzchivalrik/gentletouch#4]
Can't live without this amazing plugin, and hope it can be made compatible again soon!

**Comment by ryankhart** [comment]
@VictorFong-SE I made a pull request to this repo because I got it working for Patch 6.1.
https://github.com/fitzchivalrik/gentletouch/pull/5

If you don't want to wait for this to get released on the repo and you have Visual Studio 2022 installed (not to be confused with VS Code), you can just:
1. Go to https://github.com/ryankhart/gentletouch
2. Click the green "Code" button.
3. Click "Open with Visual Studio"
4. In Visual Studio, in the "Solution Explorer" pane, double click on "GentleTouch.sln"
5. From the Solution Configurations dropdown on the standard toolbar, choose "Release" rather than "Debug" or you'll get a debug window that appears to be impossible to close while in-game. (Other plugins don't have this issue. They just happen to log more data in the log or launch with a closeable debug window.)
![image](https://user-images.githubusercontent.com/3673962/165372093-8563f059-779c-4d3d-80da-d53498900475.png)
6. In the menu bar, click on "Build" -> "Build Solution"
7. In FFXIV launched via XIVLauncer (no restart required), go to /xlplugins
8. In /xlplugins, click settings.
9. In settings - > Experimental tab, add the full, absolute path to `[...]\[project root]\GentleTouch\bin\`
10. Click "Save and Close"
11. Install GentleTouch from the Dev Tools menu.

**Comment by fitzchivalrik** [comment]
Thank you for using the plugin. I already updated it for 6.1 but wanted to first 'fix' the way cooldowns with charges are currently handled. In hindsight, I should have released an update to 6.1 first. Sorry!

I will take time this weekend and release something either way.

**Comment by VictorFong-SE** [comment]
@ryankhart Thank you so much much for the temporary fixed! I'll go ahead and give it a try!

@fitzchivalrik Thank you also for the response, and please take as much time as you need! At first I was skeptical about how useful the vibrations would be but now life just feels incomplete without that steady pulse haha. Best!

**Comment by winkeyeblind** [comment]
Can't wait to see this get officially released again! One of the best plugins out there

**Comment by ryankhart** [comment]
Ya, I know. I thought I just missed it for finding aether currents, but feeling a rumble after every GCD has really helped me relax a bit while playing instead of spamming abilities. I can just do the abilities on the beat of the rumble.

**Comment by fitzchivalrik** [comment]
API6 Update committed & released.
